FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
# Install packages including devDependencies needed to build
RUN npm install

COPY . .
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
